---
blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://github.com/vmware/packer-plugin-vmware/discussions
    about: Need some help? Join the community discussions.
  - name: Packer Plugin Documentation
    url: https://developer.hashicorp.com/packer/integrations/vmware/vmware
    about: Having trouble with this Packer plugin? Check out the plugin documentation.
  - name: Packer Documentation
    url: https://developer.hashicorp.com/packer/
    about: Having trouble with Packer? Check out the product documentation.
